#! /bin/sh
. /etc/profile
if [ -z "$DISPLAY" ]; then
	export DISPLAY=:0.0
fi

BASE=$(cd `dirname "$0"`; pwd)
eval java -cp \"$BASE/lib/junit.jar:$BASE/testcommon/bin:$BASE/testgui/bin:$BASE/testuno/bin:$BASE/testgui/data:$BASE/testuno/data\" org.openoffice.test.Run -r org.openoffice.test.common.Installer -l org.openoffice.test.common.XMLReporter -l org.openoffice.test.common.ReportUploader \"-Dtestspace=$BASE/testspace\" -Dsingleton=true "$*"
