# MODULE.bazel
module(
    name = "aoo",
    version = "4.5.0",
)

# --------------- bazel dependencies ---------------
bazel_dep(name = "platforms",        version = "1.0.0")
bazel_dep(name = "rules_cc",         version = "0.2.17")
bazel_dep(name = "rules_foreign_cc", version = "0.15.1")
# MODULE.bazel (root) - only orchestrates, no details
bazel_dep(name = "redland",          version = "1.0.17")

bazel_dep(name = "strawberry-perl", version = "5.32.1.1")
