# BUILD  (root)
# Intentionally empty — Bazel requires this file at the workspace root.
platform(
    name = "x86_windows-clang-cl",
    constraint_values = [
        "@platforms//cpu:x86_32",
        "@platforms//os:windows",
        "@bazel_tools//tools/cpp:clang-cl",
    ],
)
