# *************************************************************
#
#  Licensed to the Apache Software Foundation (ASF) under one
#  or more contributor license agreements.  See the NOTICE file
#  distributed with this work for additional information
#  regarding copyright ownership.  The ASF licenses this file
#  to you under the Apache License, Version 2.0 (the
#  "License"); you may not use this file except in compliance
#  with the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing,
#  software distributed under the License is distributed on an
#  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#  KIND, either express or implied.  See the License for the
#  specific language governing permissions and limitations
#  under the License.
#
# *************************************************************

# This file is used to check whether the current SCons is able to
# build AOO

import sys

if sys.platform in ("cygwin", "win32"):
    try:
        import winreg
    except ImportError:
        sys.stderr.write("This version of SCons cannot detect Visual Studio "
                         "compilers (platform: %s).\n"  % sys.platform)
        sys.stderr.write("Please install native version.\n")
        sys.exit(1)
