#! /bin/sh
#**************************************************************
#  
#  Licensed to the Apache Software Foundation (ASF) under one
#  or more contributor license agreements.  See the NOTICE file
#  distributed with this work for additional information
#  regarding copyright ownership.  The ASF licenses this file
#  to you under the Apache License, Version 2.0 (the
#  "License"); you may not use this file except in compliance
#  with the License.  You may obtain a copy of the License at
#  
#    http://www.apache.org/licenses/LICENSE-2.0
#  
#  Unless required by applicable law or agreed to in writing,
#  software distributed under the License is distributed on an
#  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#  KIND, either express or implied.  See the License for the
#  specific language governing permissions and limitations
#  under the License.
#  
#**************************************************************

. /etc/profile
if [ -z "$DISPLAY" ]; then
	export DISPLAY=:0.0
fi

BASE=$(cd `dirname "$0"`; pwd)
eval java -cp \"$BASE/lib/junit.jar:$BASE/testcommon/bin:$BASE/testgui/bin:$BASE/testuno/bin:$BASE/testgui/data:$BASE/testuno/data\" org.openoffice.test.Run -r org.openoffice.test.common.Installer -l org.openoffice.test.common.XMLReporter -l org.openoffice.test.common.ReportUploader \"-Dtestspace=$BASE/testspace\" -Dsingleton=true "$*"
