/**************************************************************
 * 
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 * 
 *************************************************************/


#ifndef _SVX_FMSERVS_HXX
#define _SVX_FMSERVS_HXX

#ifndef _FM_STATIC_HXX_
#include "fmstatic.hxx"
#endif
namespace binfilter {

namespace svxform
{

	DECLARE_CONSTASCII_USTRING(FM_NUMBER_FORMATTER);

	DECLARE_CONSTASCII_USTRING(FM_COMPONENT_EDIT);		// alter service name (5.0)
	DECLARE_CONSTASCII_USTRING(FM_COMPONENT_TEXTFIELD);

	DECLARE_CONSTASCII_USTRING(FM_COMPONENT_LISTBOX);
	DECLARE_CONSTASCII_USTRING(FM_COMPONENT_COMBOBOX);
	DECLARE_CONSTASCII_USTRING(FM_COMPONENT_RADIOBUTTON);
	DECLARE_CONSTASCII_USTRING(FM_COMPONENT_GROUPBOX);
	DECLARE_CONSTASCII_USTRING(FM_COMPONENT_FIXEDTEXT);
	DECLARE_CONSTASCII_USTRING(FM_COMPONENT_COMMANDBUTTON);
	DECLARE_CONSTASCII_USTRING(FM_COMPONENT_CHECKBOX);

	DECLARE_CONSTASCII_USTRING(FM_COMPONENT_GRID);		// alter service name (5.0)
	DECLARE_CONSTASCII_USTRING(FM_COMPONENT_GRIDCONTROL);

	DECLARE_CONSTASCII_USTRING(FM_COMPONENT_IMAGEBUTTON);
	DECLARE_CONSTASCII_USTRING(FM_COMPONENT_FILECONTROL);
	DECLARE_CONSTASCII_USTRING(FM_COMPONENT_TIMEFIELD);
	DECLARE_CONSTASCII_USTRING(FM_COMPONENT_DATEFIELD);
	DECLARE_CONSTASCII_USTRING(FM_COMPONENT_NUMERICFIELD);
	DECLARE_CONSTASCII_USTRING(FM_COMPONENT_CURRENCYFIELD);
	DECLARE_CONSTASCII_USTRING(FM_COMPONENT_PATTERNFIELD);
	DECLARE_CONSTASCII_USTRING(FM_COMPONENT_FORMATTEDFIELD);

	DECLARE_CONSTASCII_USTRING(FM_COMPONENT_HIDDEN);	// alter service name (5.0)
	DECLARE_CONSTASCII_USTRING(FM_COMPONENT_HIDDENCONTROL);

	DECLARE_CONSTASCII_USTRING(FM_COMPONENT_IMAGECONTROL);

	DECLARE_CONSTASCII_USTRING(FM_CONTROL_GRID);
	DECLARE_CONSTASCII_USTRING(FM_CONTROL_GRIDCONTROL);

	DECLARE_CONSTASCII_USTRING(FM_FORM_CONTROLLER);
	DECLARE_CONSTASCII_USTRING(SRV_SDB_CONNECTION);
	DECLARE_CONSTASCII_USTRING(SRV_SDB_INTERACTION_HANDLER);

	DECLARE_CONSTASCII_USTRING(FM_SUN_COMPONENT_FORM);
	DECLARE_CONSTASCII_USTRING(FM_SUN_COMPONENT_TEXTFIELD);
	DECLARE_CONSTASCII_USTRING(FM_SUN_COMPONENT_LISTBOX);
	DECLARE_CONSTASCII_USTRING(FM_SUN_COMPONENT_COMBOBOX);
	DECLARE_CONSTASCII_USTRING(FM_SUN_COMPONENT_RADIOBUTTON);
	DECLARE_CONSTASCII_USTRING(FM_SUN_COMPONENT_GROUPBOX);
	DECLARE_CONSTASCII_USTRING(FM_SUN_COMPONENT_FIXEDTEXT);
	DECLARE_CONSTASCII_USTRING(FM_SUN_COMPONENT_COMMANDBUTTON);
	DECLARE_CONSTASCII_USTRING(FM_SUN_COMPONENT_CHECKBOX);
	DECLARE_CONSTASCII_USTRING(FM_SUN_COMPONENT_GRIDCONTROL);
	DECLARE_CONSTASCII_USTRING(FM_SUN_COMPONENT_IMAGEBUTTON);
	DECLARE_CONSTASCII_USTRING(FM_SUN_COMPONENT_FILECONTROL);
	DECLARE_CONSTASCII_USTRING(FM_SUN_COMPONENT_TIMEFIELD);
	DECLARE_CONSTASCII_USTRING(FM_SUN_COMPONENT_DATEFIELD);
	DECLARE_CONSTASCII_USTRING(FM_SUN_COMPONENT_NUMERICFIELD);
	DECLARE_CONSTASCII_USTRING(FM_SUN_COMPONENT_CURRENCYFIELD);
	DECLARE_CONSTASCII_USTRING(FM_SUN_COMPONENT_PATTERNFIELD);
	DECLARE_CONSTASCII_USTRING(FM_SUN_COMPONENT_HIDDENCONTROL);
	DECLARE_CONSTASCII_USTRING(FM_SUN_COMPONENT_IMAGECONTROL);
	DECLARE_CONSTASCII_USTRING(FM_SUN_COMPONENT_FORMATTEDFIELD);

	DECLARE_CONSTASCII_USTRING(FM_SUN_CONTROL_GRIDCONTROL);

	void ImplSmartRegisterUnoServices();

}	// namespace svxform

}//end of namespace binfilter
#endif // _SVX_FMSERVS_HXX

