#!/usr/bin/env python
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

"""Regenerate help_modules.bzl from util/<module>/makefile.mk.

The link lists are upstream's, verbatim: which .xhp pages HelpLinker compiles
into each module is NOT "every .xhp in the directory" (shared/ has pages on
disk that no module links), so the makefiles stay the source of truth and
this file is derived from them.

    python main/helpcontent2/gen_help_modules.py
"""

import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
MODULES = ["sbasic", "scalc", "schart", "sdatabase", "sdraw", "shared",
           "simpress", "smath", "swriter"]


def block(text, var):
    """Lines of a backslash-continued makefile variable."""
    # [ \t], not \s: \s would also eat the newline and any blank lines after
    # an EMPTY "VAR= \", running the parse on into whatever follows.
    m = re.search(r"^%s[ \t]*=[ \t]*\\?[ \t]*$" % var, text, re.M)
    if not m:
        return []
    out = []
    for line in text[m.end():].splitlines()[1:]:
        if not line.strip():
            break
        out.append(line.strip().rstrip("\\").strip())
        if not line.rstrip().endswith("\\"):
            break
    return [l for l in out if l]


def parse(module):
    path = os.path.join(HERE, "util", module, "makefile.mk")
    text = open(path).read()
    links = [l.replace("$/", "/") for l in block(text, "LINKLINKFILES")]
    added = {}
    for line in block(text, "LINKADDEDFILES"):
        m = re.match(r"-add\s+(\S+)\s+(\S+)", line)
        if not m:
            sys.exit("%s: cannot parse LINKADDEDFILES line %r" % (path, line))
        name, src = m.groups()
        src = src.replace("$/", "/")
        if name == module + ".jar":
            continue  # the xhp zip, built by the rule itself
        if name == module + ".tree":
            added[name] = "tree"
        elif src.startswith("$(PRJ)/source/auxiliary/LANGUAGE/"):
            added[name] = "source/auxiliary/en-US/" + src.split("/LANGUAGE/", 1)[1]
        elif src.startswith("$(COMMONMISC)/LANGUAGE/"):
            added[name] = "source/" + src.split("/LANGUAGE/", 1)[1]
        else:
            sys.exit("%s: unknown -add source %r" % (path, src))
    m = re.search(r"^ZIP1LIST=\$\(LANGDIR\)\$/(\S+)", text, re.M)
    if not m:
        sys.exit("%s: no ZIP1LIST" % path)
    jar = m.group(1).replace("$/", "/")
    return links, added, jar


def merged_pages():
    """Every page upstream's merge step delivers: the XHPFILES of each
    source/text/**/makefile.mk (tg_help.mk copies exactly those).  Pages on
    disk that no makefile lists never reach a .jar or HelpLinker's -src tree."""
    pages = []
    root = os.path.join(HERE, "source")
    for d, _, files in os.walk(os.path.join(root, "text")):
        if "makefile.mk" not in files:
            continue
        rel = os.path.relpath(d, root).replace(os.sep, "/")
        text = open(os.path.join(d, "makefile.mk")).read()
        for f in block(text, "XHPFILES"):
            if not f.endswith(".xhp"):
                sys.exit("%s/makefile.mk: unexpected XHPFILES entry %r" % (rel, f))
            if not os.path.exists(os.path.join(d, f)):
                sys.exit("%s/makefile.mk: listed page %s does not exist" % (rel, f))
            pages.append(rel + "/" + f)
    return sorted(pages)


def main():
    out = [
        "# GENERATED by gen_help_modules.py from util/<module>/makefile.mk -- do not edit.",
        "# Per help module: the .xhp pages HelpLinker links (upstream's LINKLINKFILES,",
        "# verbatim) and the extra files it adds to the module (LINKADDEDFILES, with",
        "# en-US paths resolved; \"tree\" = the update_tree.pl output), what its .jar",
        "# zips (ZIP1LIST: \"text/<dir>/*\" recursively, or one page), and every",
        "# page the merge step delivers (source/text/**/makefile.mk XHPFILES).",
        "",
        "HELP_MODULES = {",
    ]
    for module in MODULES:
        links, added, jar = parse(module)
        out.append("    %r: struct(" % module)
        out.append("        links = [")
        out.extend("            %r," % l for l in links)
        out.append("        ],")
        out.append("        jar = %r," % jar)
        out.append("        added = {")
        out.extend("            %r: %r," % kv for kv in sorted(added.items()))
        out.append("        },")
        out.append("    ),")
    out.append("}")
    out.append("")
    out.append("# Every page the merge step delivers (source/text/**/makefile.mk XHPFILES).")
    out.append("HELP_PAGES = [")
    out.extend("    %r," % p for p in merged_pages())
    out.append("]")
    # newline="\n": the checked-in file is LF; text mode on Windows would
    # write CRLF and every regeneration would churn the whole file.
    with open(os.path.join(HERE, "help_modules.bzl"), "w", newline="\n") as f:
        f.write("\n".join(out) + "\n")


if __name__ == "__main__":
    main()
