/**************************************************************
 * 
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 * 
 *************************************************************/
using namespace std;
#include "gConXcs.hxx"



/*****************************************************************************
 *********************   G C O N X C S W R A P . C X X   *********************
 *****************************************************************************
 * This includes the c code generated by flex
 *****************************************************************************/



/**********************   I M P L E M E N T A T I O N   **********************/
#include "gConXcs_yy.c"



/**********************   I M P L E M E N T A T I O N   **********************/
void convert_xcs_impl::runLex()
{
  // currently no .xcs files generate en-US translation, so stop trying
  // genxcs_lex();
}



/**********************   I M P L E M E N T A T I O N   **********************/
void convert_xcs_impl::setKey(string& sCollectedText)
{
  int    nL;
  string sHead;

  if (mbMergeMode)
    writeSourceFile(msCollector+sCollectedText);
  msCollector.clear();

  // is it to be translated
  if (sCollectedText.find("oor:localized=") == string::npos)
	return;

  // locate key (is any)
  nL = sCollectedText.find("oor:name=\"");
  if (nL == (int)string::npos)
	return;
  sHead = sCollectedText.substr(nL+10);
  nL    = sHead.find("\"");
  msKey = sHead.substr(0,nL);
}



/**********************   I M P L E M E N T A T I O N   **********************/
void convert_xcs_impl::unsetKey(string& sCollectedText)
{
  if (mbMergeMode)
    writeSourceFile(msCollector+sCollectedText);
  msCollector.clear();

  msKey.clear();
}



/**********************   I M P L E M E N T A T I O N   **********************/
void convert_xcs_impl::startCollectData(string& sCollectedText)
{
  if (mbMergeMode)
    writeSourceFile(msCollector);
  msCollector.clear();

  if (!msKey.size())
	return;
}



/**********************   I M P L E M E N T A T I O N   **********************/
void convert_xcs_impl::stopCollectData(string& sCollectedText)
{
  string sHead, sKey, sLang, sText;
  int    nL;


  // get type of tag
  msCollector += sCollectedText;
  nL = msCollector.find("<p");
  if (nL != (int)string::npos)
    sHead = msCollector.substr(nL+1, 1);
  else
  {
    nL = msCollector.find("<h");
    sHead = msCollector.substr(nL+1, 2);
  }

  // locate key and extract it
  nL    = msCollector.find("id=") +4;
  sKey  = msCollector.substr(nL, msCollector.find("\"", nL+1) - nL);
  nL    = msCollector.find("xml:lang=\"") + 10;
  sLang = msCollector.substr(nL, msCollector.find("\"", nL+1) - nL);
  nL    = msCollector.find(">") +1;
  sText = msCollector.substr(nL, msCollector.find("\"", nL+1) - nL);

  if (mbMergeMode)
  {
    // get all languages (includes en-US)
    vector<l10nMem_entry *>& cExtraLangauges = mcMemory.getLanguagesForKey(sKey);
    string                   sNewLine;
    nL = cExtraLangauges.size();

    writeSourceFile(msCollector);
    msCollector.clear();
    for (int i = 0; i < nL; ++i)
    {
      sNewLine = "\n<" + sHead + " id=\"" + sKey + "\"" + " xml:lang=\"" +
                 cExtraLangauges[i]->msLanguage + "\">" +
                 cExtraLangauges[i]->msText +
                 "</" + sHead + ">";

      writeSourceFile(sNewLine);
    }
  }
  else
    mcMemory.setEnUsKey(sKey, sText);

  mbCollectingData = false;
}  


/**********************   I M P L E M E N T A T I O N   **********************/
void convert_xcs_impl::collectData(string& sCollectedText)
{
  msCollector += sCollectedText;
  if (sCollectedText == "\n")
  {
	if (mbMergeMode)
      writeSourceFile(msCollector);
    msCollector.clear();
  }
}
