
  name: openoffice
  version: 'AOO413'
  summary: OpenOffice (unofficial) mirror snap
  description: This is the (unofficial) OpenOffice mirror snap.

  grade: edge
  confinement: devmode 

  parts:
    my-part:
      # See 'snapcraft plugins'
      plugin: nil
  
